name: Data Quality Check
on:
  schedule:
    - cron: "0 0 * * *" # Run daily at midnight

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run data validation
        run: python scripts/validate_data.py
      - name: Send notification if validation fails
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Data validation failed',
              body: 'Daily data validation check failed. Please check logs.'
            })
